site_name: Exposee

repo_url: https://github.com/dneumnn/RAKIPOEV
# repo_icon: fontawesome/brands/gitlab
nav:
    - Referenzarchitektur: 
      - Anforderungen: anforderungen.md
      - High-Level-Architecture: architecture.md
    - Building Blocks: buildingBlocks.md
    - Use-Case-Umsetzung: UseCaseUmsetzung.md
    - Referenzimplementierung: implementation.md
    - About: about.md

theme:
  name: material
  locale: de
  language: de
  custom_dir: docs/overrides
  features: 
    - navigation.instant
   
  logo: assets/flag.png
  favicon: assets/favicon.png

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Wechsle zum Dunkel-Modus

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Wechsle in den Hell-Modus

extra: 
  generator: false 
  last_updated: true

extra_css:
  - /css/stylesheets/extra.css

markdown_extensions:
  - sane_lists
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://viewer.diagrams.net/js/viewer-static.min.js
  - /javascript/drawio-reload.js

plugins:
    - drawio:
        tooltips: true
        border: 20
    - mermaid2